beet_domain: anzacatt.local
beet_root: /var/beetbox/docroot
# PHP Version defaults to 5.6
# php_version: "7.0"
php56_packages:
  - php5.6-bz2
nodejs_version: "6.x"
installed_extras_dcr: yes
installed_extras_nodejs: yes
nodejs_npm_global_packages:
  - name: grunt-cli
  - name: node-sass-globbing
  - name: postcss-object-fit-images
ruby_install_gems:
  - name: sass-globbing
